name: API Automation Tests

on:
  push:
    branches:
      - main
      - Test-1

  pull_request:
    branches:
      - main

jobs:
  run-api-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run Tests
        working-directory: TelecomApiAutomation
        run: mvn test


      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReport
          path: TelecomApiAutomation/reports